#!/usr/bin/env python

from TriAnnot.TriAnnotTaskParameters import *

class getORF (TriAnnotTaskParameters):

    def __init__(self):
        pass


    def retrieveTaskParameters(self, xmlElt):
        # Call the retrieveTaskParameters method of the parent class
        errorsList = super(self.__class__, self).retrieveTaskParameters(xmlElt)

        # Initializations
        orfFileName = self.parameters['orfFile']

        # Store the name of the sequence that will be generated by this tool
        if orfFileName in TriAnnotTaskParameters.generatedSequencesTaskId:
            errorsList.append("Task #%s wants to create an ORF sequence file named <%s> but this sequence file must already be created by a previous task !" % (self.taskId, orfFileName))
        else:
            TriAnnotTaskParameters.generatedSequencesTaskId[orfFileName] = {'taskIdentifier': self.taskId, 'sequenceType': 'ORF', 'generatedBy': 'getORF'}
            self.logger.debug("Sequence <%s> has been added to the list of sequences that will be generated during the pipeline execution" % (orfFileName))

        return errorsList
